version: '3.8'

services:
  web:
    container_name: app-ayuno
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_VERSION=v1.2.4-beta
    restart: always